version: '3.8'

services:
  easygenerator-db:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: easygenerator-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: faheem
      MONGO_INITDB_ROOT_PASSWORD: faheem
      INIT_WAIT_SEC: 3
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
